version: '3.8'

services:
  # 1. THE DATABASE (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: hotel_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: hotel_kiosk
    ports:
      - "5432:5432" # Exposed for local Prisma commands
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. THE GUI (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hotel.com
      PGADMIN_DEFAULT_PASSWORD: rootpassword
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. THE BACKEND (Node.js API)
  backend:
    build: ./backend
    container_name: hotel_backend
    restart: always
    ports:
      - "3001:3001"
      - "3002:3002"
    environment:
      # Connects to 'db' service inside Docker network
      - DATABASE_URL=postgresql://admin:rootpassword@db:5432/hotel_kiosk?schema=public
      - PORT=3001
      - HTTP_PORT=3002
      - AI_ENGINE_URL=http://ai-engine:5000
      - TTS_PUBLIC_DIR=/app/public/tts
    depends_on:
      - db
      - ai-engine
    volumes:
      - tts_audio:/app/public/tts

  # 5. AI Engine (VibeVoice)
  ai-engine:
    build: ./ai-engine
    container_name: hotel_ai_engine
    restart: always
    ports:
      - "5000:5000"
    environment:
      - HF_HOME=/root/.cache/huggingface
      - VIBEVOICE_OUTPUT_DIR=/app/output/tts
      - VIBEVOICE_MODEL_PATH=tarun7r/vibevoice-hindi-7b
    volumes:
      - tts_audio:/app/output/tts
      - C:/Users/paras/.cache/huggingface:/root/.cache/huggingface

  # 4. THE FRONTEND (React)
  frontend:
    build: ./frontend
    container_name: hotel_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: # Persist data even if containers are deleted
  tts_audio:
