"""
Defines which intents are valid on each UI screen, and example phrases
for each intent used by the semantic classifier.

HOW TO ADD NEW EXAMPLES:
  - Add more strings to any intent's list below.
  - More examples = better accuracy.
  - Include realistic paraphrases, slang, and STT error patterns.
  - Re-run embed_intent_examples() after any change.
"""

# Only these intents will be considered on each screen.
# This prevents "yes" on WELCOME from triggering CONFIRM_BOOKING.
VALID_INTENTS_PER_SCREEN: dict[str, list[str]] = {
    "IDLE": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY"],
    "WELCOME": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY", "IDLE"],
    "AI_CHAT": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY", "CANCEL_BOOKING"],
    "MANUAL_MENU": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY"],
    "ROOM_SELECT": ["BOOK_ROOM", "GENERAL_QUERY", "CANCEL_BOOKING"],
    "ROOM_PREVIEW": ["BOOK_ROOM", "CONFIRM_BOOKING", "CANCEL_BOOKING", "MODIFY_BOOKING", "GENERAL_QUERY"],
    "BOOKING_COLLECT": [
        "PROVIDE_GUESTS",
        "PROVIDE_DATES",
        "PROVIDE_NAME",
        "MODIFY_BOOKING",
        "CANCEL_BOOKING",
        "GENERAL_QUERY",
    ],
    "BOOKING_SUMMARY": ["CONFIRM_BOOKING", "MODIFY_BOOKING", "CANCEL_BOOKING"],
    "PAYMENT": ["CONFIRM_BOOKING", "CANCEL_BOOKING"],
    "SCAN_ID": ["CANCEL_BOOKING", "GENERAL_QUERY"],
    "ID_VERIFY": ["CONFIRM_BOOKING", "CANCEL_BOOKING", "GENERAL_QUERY"],
    "CHECK_IN_SUMMARY": ["CONFIRM_BOOKING", "MODIFY_BOOKING", "CANCEL_BOOKING"],
}

# These are embedded at startup. The semantic classifier finds the nearest intent.
# IMPORTANT: Add diverse examples. Include:
#   - Formal phrasing
#   - Casual / slang phrasing
#   - Hinglish phrasing
#   - Common STT error patterns (e.g., "tour" -> "true", "suite" -> "sweet")
INTENT_EXAMPLES: dict[str, list[str]] = {
    "BOOK_ROOM": [
        "book a room",
        "I want to book a room",
        "I'd like to make a reservation",
        "show me rooms",
        "show me the rooms",
        "what rooms do you have",
        "let me see the rooms",
        "I want to see room options",
        "virtual tour",
        "give me a virtual tour",
        "virtual true of rooms",
        "virtual tour of your rooms",
        "explore rooms",
        "can I browse the rooms",
        "what's available",
        "available rooms please",
        "I want to stay here tonight",
        "room dikh ao",
        "room book karna hai",
        "room dikhao mujhe",
        "can you show me what rooms you have",
        "I need a place to sleep",
        "need a room for tonight",
        "looking for accommodation",
    ],
    "CHECK_IN": [
        "check in",
        "I want to check in",
        "I have a reservation",
        "I have a booking",
        "existing booking",
        "I already booked",
        "my reservation",
        "get my room key",
        "I'm checking in",
        "check me in",
        "here to check in",
        "check in karna hai",
        "mera reservation hai",
        "I booked online",
        "I made a booking last week",
        "need to get my key card",
    ],
    "GENERAL_QUERY": [
        "hello",
        "hi",
        "good morning",
        "what can you do",
        "help me",
        "what is the pool timing",
        "where is the gym",
        "what time is breakfast",
        "how do I get to the restaurant",
        "what is the wifi password",
        "tell me about the hotel",
        "what amenities do you have",
        "what time is checkout",
        "I have a question",
        "can you help me",
        "what are the facilities",
        "show me the bathroom",
        "show me the balcony",
        "I want to see the bedroom",
        "show me the view",
        "show me the pool",
        "show me the minibar",
        "what does the bathroom look like",
        "can I see the balcony",
    ],
    "CONFIRM_BOOKING": [
        "yes",
        "confirm",
        "yes please confirm",
        "that looks good",
        "that is correct",
        "looks good to me",
        "proceed",
        "go ahead",
        "I agree",
        "book it",
        "confirm the booking",
        "yes I want to proceed",
        "pay",
        "I want to pay",
        "charge my card",
        "yes book the room",
        "haan",
        "haan confirm karo",
        "sahi hai",
    ],
    "CANCEL_BOOKING": [
        "cancel",
        "I want to cancel",
        "stop",
        "no thanks",
        "I don't want this",
        "go back to the start",
        "start over",
        "I changed my mind",
        "forget it",
        "never mind",
        "main cancel karna chahta hoon",
        "nahi chahiye",
    ],
    "MODIFY_BOOKING": [
        "change something",
        "I want to change the dates",
        "modify my booking",
        "that was wrong",
        "I made a mistake",
        "update the name",
        "change the room",
        "not correct",
        "that is wrong",
        "I want to change the number of guests",
        "edit the details",
        "wrong dates",
        "badal na hai",
        "show me another option",
        "show me other options",
        "I want a different room",
        "show me other rooms",
        "what else do you have",
        "not this one",
        "next room please",
        "I don't like this room",
        "go back to room selection",
        "any other options",
        "something else",
        "another one",
        "let me see the other room",
        "nahi yeh nahi doosra dikhao",
        "doosra room dikhao",
    ],
    "PROVIDE_GUESTS": [
        "2 adults",
        "two adults",
        "three guests",
        "just me",
        "1 person",
        "I'm alone",
        "my family of 4",
        "4 people",
        "two people and one child",
        "we are 3",
        "do log",
        "teen log",
        "with my wife",
        "just the two of us",
    ],
    "PROVIDE_DATES": [
        "March 20",
        "20th of March",
        "next Friday",
        "tomorrow",
        "from April 1 to April 5",
        "check in on the 15th",
        "leaving on Sunday",
        "3 nights",
        "for two nights",
        "from tomorrow for 3 days",
        "kal se",
        "teen raatein",
        "April 1st checkout April 4th",
    ],
    "PROVIDE_NAME": [
        "my name is John",
        "John Smith",
        "the booking is under Sarah Johnson",
        "it's under my wife's name, Maria",
        "Aditya Kumar",
        "the reservation is under Ahmed",
        "mera naam Rahul hai",
    ],
    "IDLE": [
        "hmm",
        "uh",
        "um",
        "ah",
        "ok",
        "okay",
        "sure",
        "",
    ],
}
