"""
Defines which intents are valid on each UI screen, and example phrases
for each intent used by the semantic classifier.

HOW TO ADD NEW EXAMPLES:
  - Add more strings to any intent's list below.
  - More examples = better accuracy.
  - Include realistic paraphrases, slang, and STT error patterns.
  - Re-run embed_intent_examples() after any change.
"""

# Only these intents will be considered on each screen.
# This prevents "yes" on WELCOME from triggering CONFIRM_BOOKING.
VALID_INTENTS_PER_SCREEN: dict[str, list[str]] = {
    "IDLE": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY", "REQUEST_HELP"],
    "WELCOME": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY", "IDLE", "REQUEST_HELP"],
    "AI_CHAT": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY", "CANCEL_BOOKING", "REQUEST_HELP"],
    "MANUAL_MENU": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY"],
    "ROOM_SELECT": ["BOOK_ROOM", "GENERAL_QUERY", "CANCEL_BOOKING", "REQUEST_HELP"],
    "ROOM_PREVIEW": [
        "BOOK_ROOM",
        "CONFIRM_BOOKING",
        "CANCEL_BOOKING",
        "MODIFY_BOOKING",
        "GENERAL_QUERY",
        "PROVIDE_GUESTS",
        "PROVIDE_DATES",
        "PROVIDE_NAME",
        "OPEN_FULLSCREEN_GALLERY",
        "CLOSE_FULLSCREEN_GALLERY",
    ],
    "BOOKING_COLLECT": [
        "PROVIDE_GUESTS",
        "PROVIDE_DATES",
        "PROVIDE_NAME",
        "CONFIRM_BOOKING",
        "MODIFY_BOOKING",
        "CANCEL_BOOKING",
        "GENERAL_QUERY",
        "REQUEST_HELP",
    ],
    "BOOKING_SUMMARY": ["CONFIRM_BOOKING", "MODIFY_BOOKING", "CANCEL_BOOKING", "REQUEST_HELP"],
    "PAYMENT": ["CONFIRM_BOOKING", "CANCEL_BOOKING"],
    "SCAN_ID": ["CANCEL_BOOKING", "GENERAL_QUERY"],
    "ID_VERIFY": ["CONFIRM_BOOKING", "CANCEL_BOOKING", "GENERAL_QUERY"],
    "CHECK_IN_SUMMARY": ["CONFIRM_BOOKING", "MODIFY_BOOKING", "CANCEL_BOOKING"],
}

# These are embedded at startup. The semantic classifier finds the nearest intent.
# IMPORTANT: Add diverse examples. Include:
#   - Formal phrasing
#   - Casual / slang phrasing
#   - Hinglish phrasing
#   - Common STT error patterns (e.g., "tour" -> "true", "suite" -> "sweet")
INTENT_EXAMPLES: dict[str, list[str]] = {
    "BOOK_ROOM": [
        "book a room",
        "I want to book a room",
        "I'd like to make a reservation",
        "we are a family of four which room should we look at",
        "which room would be best for two adults and two children",
        "recommend a room for my family",
        "suggest a room for two adults and one child",
        "what is your cheapest room",
        "what is your most affordable room",
        "which room should I choose",
        "compare the deluxe king and the family suite",
        "please show me the family suite",
        "show me the deluxe king",
        "book this room",
        "I'll take this room",
        "I want this one",
        "show me rooms",
        "show me the rooms",
        "what rooms do you have",
        "let me see the rooms",
        "I want to see room options",
        "virtual tour",
        "give me a virtual tour",
        "virtual true of rooms",
        "virtual tour of your rooms",
        "explore rooms",
        "can I browse the rooms",
        "what's available",
        "available rooms please",
        "I want to stay here tonight",
        "room dikh ao",
        "room book karna hai",
        "room dikhao mujhe",
        "can you show me what rooms you have",
        "I need a place to sleep",
        "need a room for tonight",
        "looking for accommodation",
    ],
    "CHECK_IN": [
        "check in",
        "I want to check in",
        "I have a reservation",
        "I have a booking",
        "existing booking",
        "I already booked",
        "my reservation",
        "get my room key",
        "I'm checking in",
        "check me in",
        "here to check in",
        "check in karna hai",
        "mera reservation hai",
        "I booked online",
        "I made a booking last week",
        "need to get my key card",
    ],
    "GENERAL_QUERY": [
        "hello",
        "hi",
        "good morning",
        "what can you do",
        "help me",
        "what is the pool timing",
        "where is the gym",
        "what time is breakfast",
        "how do I get to the restaurant",
        "what is the wifi password",
        "tell me about the hotel",
        "what amenities do you have",
        "what time is checkout",
        "I have a question",
        "can you help me",
        "what are the facilities",
        "show me the bathroom",
        "show me the balcony",
        "I want to see the bedroom",
        "show me the view",
        "show me the pool",
        "show me the minibar",
        "what does the bathroom look like",
        "can I see the balcony",
    ],
    "REQUEST_HELP": [
        "I need help",
        "Call the manager",
        "Talk to a human",
        "Where is the staff",
        "Support",
        "assist me please",
        "I need staff assistance",
        "can someone help me here",
        "connect me to support",
        "call someone from the front desk",
    ],
    "OPEN_FULLSCREEN_GALLERY": [
        # Standard English
        "I want to see the fullscreen view of the images",
        "show me the images in full screen",
        "make the picture bigger",
        "open full view",
        "expand the image",
        "show gallery",
        "zoom in",
        "zoom in on the picture",
        "can I see the photos closer",
        "view gallery",
        "maximize image",
        "enlarge photo",
        # Casual / Short commands
        "bigger",
        "full screen",
        "show pics",
        "let me see the pictures",
        # Hinglish Support
        "bada karke dikhao",
        "puri screen pe dikhao",
        "photo badi karo",
        "gallery kholo",
        "images dikhao",
        "full screen kardo",
        "aur paas se dikhao",
        # Common STT Errors
        "pool screen",
        "pull screen",
        "resume in",
        "make it figure",
        "full stream",
    ],
    "CLOSE_FULLSCREEN_GALLERY": [
        # Standard English
        "close the image",
        "close full screen",
        "exit full screen",
        "go back to the room details",
        "minimize the photo",
        "close gallery",
        # Casual / Short commands
        "close it",
        "ok",
        "okay",
        "that's enough",
        "done looking",
        "go back",
        "exit",
        "hide images",
        # Hinglish Support
        "band karo",
        "hatao isko",
        "wapas jao",
        "bas karo",
        "okay band kar do",
        "image hatao",
        "back chalo",
        # Common STT Errors
        "clothes",
        "clothes it",
        "glows",
        "ex it",
        "go bag",
    ],
    "CONFIRM_BOOKING": [
        "yes",
        "confirm",
        "yes those details are correct",
        "yes everything is correct proceed to payment",
        "please proceed to payment",
        "that is correct take me to payment",
        "go to payment",
        "yes please confirm",
        "that looks good",
        "that is correct",
        "looks good to me",
        "proceed",
        "go ahead",
        "I agree",
        "book it",
        "confirm the booking",
        "yes I want to proceed",
        "pay",
        "I want to pay",
        "charge my card",
        "yes book the room",
        "haan",
        "haan confirm karo",
        "sahi hai",
    ],
    "CANCEL_BOOKING": [
        "cancel",
        "I want to cancel",
        "stop",
        "no thanks",
        "I don't want this",
        "go back to the start",
        "start over",
        "I changed my mind",
        "forget it",
        "never mind",
        "main cancel karna chahta hoon",
        "nahi chahiye",
    ],
    "MODIFY_BOOKING": [
        "change something",
        "I want to change the dates",
        "modify my booking",
        "I need to change the guest name before paying",
        "change the guest name before payment",
        "update the booking details before payment",
        "edit the guest details",
        "go back and edit the details",
        "that was wrong",
        "I made a mistake",
        "update the name",
        "change the room",
        "not correct",
        "that is wrong",
        "I want to change the number of guests",
        "edit the details",
        "wrong dates",
        "badal na hai",
        "show me another option",
        "show me other options",
        "I want a different room",
        "show me other rooms",
        "what else do you have",
        "not this one",
        "next room please",
        "I don't like this room",
        "go back to room selection",
        "any other options",
        "something else",
        "another one",
        "let me see the other room",
        "nahi yeh nahi doosra dikhao",
        "doosra room dikhao",
    ],
    "PROVIDE_GUESTS": [
        "2 adults",
        "two adults",
        "two adults and one child",
        "two adults and two children",
        "the booking is for two adults and one child",
        "three guests",
        "just me",
        "1 person",
        "I'm alone",
        "my family of 4",
        "4 people",
        "two people and one child",
        "we are 3",
        "do log",
        "teen log",
        "with my wife",
        "just the two of us",
    ],
    "PROVIDE_DATES": [
        "March 20",
        "20th of March",
        "checking in tomorrow for two nights",
        "check in tomorrow for two nights",
        "we want to check in tomorrow for two nights",
        "next Friday",
        "tomorrow",
        "from April 1 to April 5",
        "check in on the 15th",
        "leaving on Sunday",
        "3 nights",
        "for two nights",
        "from tomorrow for 3 days",
        "kal se",
        "teen raatein",
        "April 1st checkout April 4th",
    ],
    "PROVIDE_NAME": [
        "my name is John",
        "John Smith",
        "my name is John Carter two adults checking in tomorrow for two nights",
        "the booking is for John Carter two adults and one child tomorrow for two nights",
        "the booking is under Sarah Johnson",
        "it's under my wife's name, Maria",
        "Aditya Kumar",
        "the reservation is under Ahmed",
        "mera naam Rahul hai",
    ],
    "IDLE": [
        "hmm",
        "uh",
        "um",
        "ah",
        "ok",
        "okay",
        "sure",
        "",
    ],
}
