"""
Intent routing and semantic-classifier configuration.

This file separates three concerns cleanly:

VALID_INTENTS_PER_SCREEN
    Routing gate: which intents are even possible on each screen.

INTENT_METADATA
    Per-intent settings such as display name, minimum confidence, and
    whether lower-confidence matches should fall through to the LLM router.

INTENT_EXAMPLES
    Embedding examples used by the semantic classifier.
"""

from __future__ import annotations


# ---------------------------------------------------------------------------
# Screen routing gate
# ---------------------------------------------------------------------------

VALID_INTENTS_PER_SCREEN: dict[str, list[str]] = {
    "IDLE": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY"],
    "WELCOME": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY", "IDLE"],
    "AI_CHAT": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY", "CANCEL_BOOKING"],
    "MANUAL_MENU": ["BOOK_ROOM", "CHECK_IN", "GENERAL_QUERY"],
    "ROOM_SELECT": [
        "BOOK_ROOM",
        "GENERAL_QUERY",
        "CANCEL_BOOKING",
        "PROVIDE_GUESTS",
        "PROVIDE_DATES",
    ],
    "ROOM_PREVIEW": [
        "BOOK_ROOM",
        "CONFIRM_BOOKING",
        "CANCEL_BOOKING",
        "MODIFY_BOOKING",
        "GENERAL_QUERY",
        "PROVIDE_GUESTS",
        "PROVIDE_DATES",
        "PROVIDE_NAME",
    ],
    "BOOKING_COLLECT": [
        "PROVIDE_GUESTS",
        "PROVIDE_DATES",
        "PROVIDE_NAME",
        "CONFIRM_BOOKING",
        "MODIFY_BOOKING",
        "CANCEL_BOOKING",
        "GENERAL_QUERY",
    ],
    "BOOKING_SUMMARY": ["CONFIRM_BOOKING", "MODIFY_BOOKING", "CANCEL_BOOKING"],
    "PAYMENT": ["CONFIRM_BOOKING", "CANCEL_BOOKING"],
    "SCAN_ID": ["CANCEL_BOOKING", "GENERAL_QUERY"],
    "ID_VERIFY": ["CONFIRM_BOOKING", "CANCEL_BOOKING", "GENERAL_QUERY"],
    "CHECK_IN_SUMMARY": ["CONFIRM_BOOKING", "MODIFY_BOOKING", "CANCEL_BOOKING"],
}


# ---------------------------------------------------------------------------
# Per-intent metadata
# ---------------------------------------------------------------------------

INTENT_METADATA: dict[str, dict[str, object]] = {
    "BOOK_ROOM": {"display": "Book a room", "min_confidence": 0.45, "llm_fallback": False},
    "CHECK_IN": {"display": "Check in", "min_confidence": 0.50, "llm_fallback": False},
    "GENERAL_QUERY": {"display": "General question", "min_confidence": 0.40, "llm_fallback": False},
    "CONFIRM_BOOKING": {"display": "Confirm booking", "min_confidence": 0.60, "llm_fallback": True},
    "CANCEL_BOOKING": {"display": "Cancel", "min_confidence": 0.50, "llm_fallback": False},
    "MODIFY_BOOKING": {"display": "Modify booking", "min_confidence": 0.50, "llm_fallback": False},
    "PROVIDE_GUESTS": {"display": "Guest count", "min_confidence": 0.45, "llm_fallback": False},
    "PROVIDE_DATES": {"display": "Stay dates", "min_confidence": 0.45, "llm_fallback": False},
    "PROVIDE_NAME": {"display": "Guest name", "min_confidence": 0.45, "llm_fallback": False},
    "IDLE": {"display": "Idle / no-op", "min_confidence": 0.35, "llm_fallback": False},
}


# ---------------------------------------------------------------------------
# Intent examples
# ---------------------------------------------------------------------------

INTENT_EXAMPLES: dict[str, list[str]] = {
    "BOOK_ROOM": [
        "I would like to book a room",
        "I'd like to make a reservation",
        "I want to reserve a room for two nights",
        "Can I book a room for tonight",
        "I need accommodation for three nights",
        "We are looking for a room",
        "I would like to see your available rooms",
        "Please show me your room options",
        "book a room",
        "show me rooms",
        "what rooms do you have",
        "show me the rooms",
        "let me see the rooms",
        "I want to see room options",
        "what's available",
        "available rooms please",
        "I want to stay here tonight",
        "need a room for tonight",
        "looking for accommodation",
        "book this room",
        "I'll take this room",
        "I want this one",
        "can I browse the rooms",
        "show me the family suite",
        "show me the deluxe king",
        "I need a place to sleep",
        "we are a family of four which room should we look at",
        "which room would be best for two adults and two children",
        "recommend a room for my family",
        "suggest a room for two adults and one child",
        "what is your cheapest room",
        "what is your most affordable room",
        "which room should I choose",
        "compare the deluxe king and the family suite",
        "what is the difference between the rooms",
        "which room is better for a couple",
        "virtual tour",
        "give me a virtual tour",
        "virtual tour of your rooms",
        "explore rooms",
        "can you walk me through the rooms",
        "room dikh ao",
        "room book karna hai",
        "room dikhao mujhe",
        "ek room chahiye",
        "room book karo",
        "koi acha room dikhao",
        "do log ke liye room chahiye",
    ],
    "CHECK_IN": [
        "I would like to check in",
        "I have an existing reservation",
        "I have a confirmed booking",
        "I booked a room online",
        "I made a reservation last week",
        "I need to collect my room key",
        "I need to get my key card",
        "I am here to check in",
        "check in",
        "I have a reservation",
        "I have a booking",
        "existing booking",
        "I already booked",
        "my reservation",
        "get my room key",
        "I'm checking in",
        "check me in",
        "here to check in",
        "I booked online",
        "my reservations",
        "check in karna hai",
        "mera reservation hai",
        "meri booking hai",
        "key leni hai",
        "pehle se book kiya hua hai",
    ],
    "GENERAL_QUERY": [
        "hello",
        "hi",
        "good morning",
        "good evening",
        "hey there",
        "what can you do",
        "help me",
        "I have a question",
        "can you help me",
        "what is the pool timing",
        "where is the gym",
        "what time is breakfast",
        "how do I get to the restaurant",
        "what is the wifi password",
        "tell me about the hotel",
        "what amenities do you have",
        "what time is checkout",
        "what are the facilities",
        "is there a spa",
        "is there parking available",
        "do you have a swimming pool",
        "what is the checkout time",
        "what time does the restaurant open",
        "is breakfast included",
        "show me the bathroom",
        "show me the balcony",
        "I want to see the bedroom",
        "show me the view",
        "show me the pool",
        "show me the minibar",
        "what does the bathroom look like",
        "can I see the balcony",
        "show me what the room looks like",
        "tell me more about this room",
        "what features does this room have",
        "does the room have a bathtub",
        "does it have air conditioning",
        "wifi ka password kya hai",
        "breakfast kab hai",
        "pool kab khulta hai",
    ],
    "CONFIRM_BOOKING": [
        "yes",
        "yes please confirm",
        "confirm",
        "confirm the booking",
        "yes book the room",
        "yes those details are correct",
        "yes everything is correct proceed to payment",
        "please proceed to payment",
        "that is correct take me to payment",
        "go to payment",
        "that looks good",
        "that is correct",
        "looks good to me",
        "proceed",
        "go ahead",
        "I agree",
        "book it",
        "yes I want to proceed",
        "pay",
        "I want to pay",
        "charge my card",
        "take me to payment",
        "process the payment",
        "I'm ready to pay",
        "everything is correct",
        "the details are right",
        "that's right go ahead",
        "yes all correct",
        "yes that's fine",
        "perfect go ahead",
        "haan",
        "haan confirm karo",
        "sahi hai",
        "theek hai confirm karo",
        "haan bilkul",
        "haan proceed karo",
    ],
    "CANCEL_BOOKING": [
        "cancel",
        "I want to cancel",
        "cancel my booking",
        "stop",
        "no thanks",
        "I don't want this",
        "I don't want to continue",
        "go back to the start",
        "start over",
        "restart",
        "take me back to the beginning",
        "reset",
        "I changed my mind",
        "forget it",
        "never mind",
        "actually no",
        "leave it",
        "abort",
        "stop everything",
        "I want to leave",
        "exit",
        "quit",
        "no I don't want this room",
        "this isn't what I want",
        "just cancel it",
        "please cancel",
        "main cancel karna chahta hoon",
        "nahi chahiye",
        "band karo",
        "rukao",
        "nahi karna",
        "wapas jana hai",
    ],
    "MODIFY_BOOKING": [
        "change something",
        "I need to make a change",
        "I want to update the booking",
        "edit the details",
        "modify my booking",
        "update the booking details before payment",
        "go back and edit the details",
        "I want to change the dates",
        "wrong dates",
        "I need to change the guest name before paying",
        "change the guest name before payment",
        "update the name",
        "I want to change the number of guests",
        "I made a mistake",
        "that was wrong",
        "not correct",
        "that is wrong",
        "change the room",
        "show me another option",
        "show me other options",
        "I want a different room",
        "show me other rooms",
        "what else do you have",
        "not this one",
        "next room please",
        "I don't like this room",
        "go back to room selection",
        "any other options",
        "something else",
        "another one",
        "let me see the other room",
        "I'd prefer a different room",
        "badal na hai",
        "nahi yeh nahi doosra dikhao",
        "doosra room dikhao",
        "naam change karna hai",
        "date change karni hai",
        "galti ho gayi",
    ],
    "PROVIDE_GUESTS": [
        "1 adult",
        "2 adults",
        "3 adults",
        "4 adults",
        "1 person",
        "2 people",
        "3 people",
        "4 people",
        "just me",
        "only me",
        "I'm alone",
        "one adult",
        "two adults",
        "three adults",
        "four adults",
        "two adults and one child",
        "two adults and two children",
        "three guests",
        "the booking is for two adults and one child",
        "my family of 4",
        "we are 3",
        "just the two of us",
        "with my wife",
        "with my partner",
        "me and my husband",
        "me and my wife and two kids",
        "our family of five",
        "couple with no children",
        "two adults no kids",
        "do log",
        "teen log",
        "char log",
        "sirf main",
        "main aur meri wife",
        "do adult aur ek bachcha",
    ],
    "PROVIDE_DATES": [
        "March 20",
        "20th of March",
        "April 1st checkout April 4th",
        "check in on the 15th",
        "the 10th to the 14th",
        "from April 1 to April 5",
        "arriving on the 3rd leaving on the 7th",
        "tomorrow",
        "tonight",
        "this weekend",
        "next Friday",
        "next Monday",
        "end of the month",
        "this coming Saturday",
        "from tomorrow for 3 days",
        "checking in tomorrow for two nights",
        "check in tomorrow for two nights",
        "we want to check in tomorrow for two nights",
        "leaving on Sunday",
        "3 nights",
        "for two nights",
        "for one night",
        "just one night",
        "a week",
        "for 4 days",
        "for a long weekend",
        "kal se",
        "kal se do raat",
        "teen raatein",
        "is weekend ke liye",
        "aaj raat ke liye",
        "March twenty",
        "twenty first of March",
    ],
    "PROVIDE_NAME": [
        "my name is John",
        "John Smith",
        "it's Sarah Johnson",
        "the booking is under Sarah Johnson",
        "the name is Michael Brown",
        "my name is Emily Davis",
        "Mary-Jane Watson",
        "it's under Jean-Pierre Dupont",
        "the reservation is for Anne Marie",
        "the booking is under my wife's name Maria",
        "it's under my husband Robert",
        "it's in my name David",
        "under the name of Mr Patel",
        "Mrs Sharma",
        "Aditya Kumar",
        "Rahul Sharma",
        "Priya Nair",
        "Ananya Krishnamurthy",
        "Rohit Verma",
        "Sunita Rao",
        "mera naam Rahul hai",
        "naam Aditya Kumar hai",
        "Ahmed Al-Rashid",
        "the reservation is under Ahmed",
        "Mohammed Hassan",
        "Fatima Al-Zahra",
        "my name is Jon",
        "Patel",
        "it's under Sharma",
        "the booking is for john carter two adults checking in tomorrow for two nights",
        "the booking is for John Carter two adults and one child tomorrow for two nights",
        "my name is John Carter two adults checking in tomorrow for two nights",
        "booking Amit ke naam pe hai",
        "naam Priya Sharma hai",
    ],
    "IDLE": [
        "hmm",
        "uh",
        "um",
        "ah",
        "er",
        "uhh",
        "umm",
        "ok",
        "okay",
        "sure",
        "",
        "yeah",
        "right",
        "wait",
        "give me a second",
        "just a moment",
        "hold on",
        "one sec",
        "let me think",
        "hmm let me think",
        "I'm not sure",
        "uh let me see",
        "theek hai",
        "ruko",
        "ek second",
    ],
}


def get_valid_intents(screen: str) -> list[str]:
    """Return the intents allowed on a given UI screen."""
    return VALID_INTENTS_PER_SCREEN.get(screen, list(INTENT_EXAMPLES.keys()))


def get_min_confidence(intent: str) -> float:
    """Return the minimum confidence threshold for an intent."""
    metadata = INTENT_METADATA.get(intent, {})
    return float(metadata.get("min_confidence", 0.45))


def should_llm_fallback(intent: str) -> bool:
    """Return True when medium-confidence matches should defer to the LLM router."""
    metadata = INTENT_METADATA.get(intent, {})
    return bool(metadata.get("llm_fallback", False))


def intent_display_name(intent: str) -> str:
    """Return a human-readable intent label."""
    metadata = INTENT_METADATA.get(intent, {})
    return str(metadata.get("display", intent))
