export type Intent =
    | "PROXIMITY_DETECTED"
    | "VOICE_STARTED"
    | "VOICE_TRANSCRIPT_RECEIVED"
    | "VOICE_SILENCE"
    | "TOUCH_SELECTED"
    | "CHECK_IN_SELECTED"
    | "BOOK_ROOM_SELECTED"
    | "BACK_REQUESTED"
    | "CANCEL_REQUESTED";
